### ISSUE TITLE
hacer los controladores

### ISSUE THREAD

**Issue by JosueMTL** [JosueMTL/Alzheimer-s-project#7]
hacer hoy sea como sea 🤑🤑🤑🤑😒😒

**Comment by JosueMTL** [comment]
ya que @jonatanjc haya hecho los services puede avanzar carlos con los controladores porque ya @JosueMTL le dio paso a @jonatanjc y esperar ser notificados a que las fueron unidas

**Comment by carlosduti70** [comment]
ya lo empiezo y termino ahora mismo
